### ISSUE TITLE
测试数据的时候出现图中的问题

### ISSUE THREAD

**Issue by marico2020** [dawnyc/ROMTrack#1]
![Uploading IMG_7970.jpeg…]()

**Comment by marico2020** [comment]
运行test.py 出现'NoneType' object is not callale问题

**Comment by thinker9527** [comment]
请问上面这个问题。你解决了么？

**Comment by dawnyc** [comment]
We feel sorry to have made such a mistake, and now we have fixed it, see the new file (https://github.com/dawnyc/ROMTrack/blob/master/lib/test/tracker/ROMTrack.py).
