### ISSUE TITLE
分阶段训练问题

### ISSUE THREAD

**Issue by Xirui-Chen** [dawnyc/ROMTrack#15]
您好，请问为何训练要分阶段呢，为什么不直接全程采用 variation tokens进行训练呢，是为了对比实验，还是说这样效果会更好

**Comment by dawnyc** [comment]
The original backbone (ViT pretrained with MAE) has poor performance on tracking if not trained on visual tracking dataset. As a result, variation tokens extract directly from the beginning will has poor semantic informations. This will hinder the training process of the model. On the contrary, if we seperate it into 2 stages, the training process will be more smooth and steady. Moreover, it is also more convient for users to evaluate both stage1 and stage2 models.

**Comment by Xirui-Chen** [comment]
非常感谢您的解答，我似乎理解了为何要先经过第一阶段的训练，在开始第二阶段的训练了；我想表达下我的理解，不知道是否正确，若有错误，还请您解答下：
如果不经过先经过第一阶段visual tracking dataset的训练，那么在第二阶段模型就无法生成有效的variation tokens，这种低效的varition tokens反而会阻碍模型的精度

**Comment by dawnyc** [comment]
Yeah, you are totally right.
