### ISSUE TITLE
results 

### ISSUE THREAD

**Issue by Clarkwk** [dawnyc/ROMTrack#5]
Hello, I encountered the following issues while testing OTB100 dataset: In ### OTB100

# python tracking/test.py ROMTrack baseline_stage2 --dataset otb --threads 32 --num_gpus 8 --params__model  ROMTrack_epoch0100.pth.tar --params__search_area_scale 3.65

# python tracking/analysis_results.py --dataset_name otb --tracker_param baseline_stage2, With this parameter --params__search_area_scale 3.65, the results are still the same after removing it

**Comment by dawnyc** [comment]
Sorry but in our experiments on OTB, the results for scale=3.65 (AUC=71.4%) are different from results for scale=4.0 (AUC=70.8%). Please check 2 aspects that maybe lead to your phenomena.

  1) Make sure that you have removed the old result files when you test a new one. The default directory to save result files are the same, so if the old result files exist in this directory, no new result files will be generated.

  2) Check the GPU hardware. Our devices are 1080ti and v100. There is no guarantee that you can get the same results on different GPU devices or enviroments.

Hope this will help you.
