### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by Clarkwk** [dawnyc/ROMTrack#6]
Hello, I got ROMTrack_ep0050.pth.tar after training got_stage2 with a single GPU, but during testing, I had the following error, Error(s) in loading state_dict for ROMTrack:
	Missing key(s) in state_dict: "encoder.pos_embed_t", "encoder.pos_embed_s", "encoder.patch_embed_t.proj.weight", "encoder.patch_embed_t.proj.bias", "encoder.blocks.0.norm1.weight", "encoder.blocks.0.norm1.bias", "encoder.blocks.0.attn.qkv.weight", "encoder.blocks.0.attn.qkv.bias", "encoder.blocks.0.attn.proj.weight", "encoder.blocks.0.attn.proj.bias", "encoder.blocks.0.norm2.weight", "encoder.blocks.0.norm2.bias", "encoder.blocks.0.mlp.fc1.weight", "encoder.blocks.0.mlp.fc1.bias", "encoder.blocks.0.mlp.fc2.weight", "encoder.blocks.0.mlp.fc2.bias", "encoder.blocks.1.norm1.weight", "encoder.blocks.1.norm1.bias", "encoder.blocks.1.attn.qkv.weight", "encoder.blocks.1.attn.qkv.bias", "encoder.blocks.1.attn.proj.weight", "encoder.blocks.1.attn.proj.bias", "encoder.blocks.1.norm2.weight", "encoder.blocks.1.norm2.bias", "encoder.blocks.1.mlp.fc1.weight", "encoder.blocks.1.mlp.fc1.bias", "encoder.blocks.1.mlp.fc2.weight", "encoder.blocks.1.mlp.fc2.bias", "encoder.blocks.2.norm1.weight", "encoder.blocks.2.norm1.bias", "encoder.blocks.2.attn.qkv.weight", "encoder.blocks.2.attn.qkv.bias", "encoder.blocks.2.attn.proj.weight", "encoder.blocks.2.attn.proj.bias", "encoder.blocks.2.norm2.weight", "encoder.blocks.2.norm2.bias", "encoder.blocks.2.mlp.fc1.weight", "encoder.blocks.2.mlp.fc1.bias", "encoder.blocks.2.mlp.fc2.weight", "encoder.blocks.2.mlp.fc2.bias", "encoder.blocks.3.norm1.weight", "encoder.blocks.3.norm1.bias", "encoder.blocks.3.attn.qkv.weight", "encoder.blocks.3.attn.qkv.bias", "encoder.blocks.3.attn.proj.weight", "encoder.blocks.3.attn.proj.bias", "encoder.blocks.3.norm2.weight", "encoder.blocks.3.norm2.bias", "encoder.blocks.3.mlp.fc1.weight", "encoder.blocks.3.mlp.fc1.bias", "encoder.blocks.3.mlp.fc2.weight", "encoder.blocks.3.mlp.fc2.bias", "encoder.blocks.4.norm1.weight", "encoder.blocks.4.norm1.bias", "encoder.blocks.4.attn.qkv.weight", "encoder.blocks.4.attn.qkv.bias", "encoder.blocks.4.attn.proj.weight", "encoder.blocks.4.attn.proj.bias", "encoder.blocks.4.norm2.weight", "encoder.blocks.4.norm2.bias", "encoder.blocks.4.mlp.fc1.weight", "encoder.blocks.4.mlp.fc1.bias", "encoder.blocks.4.mlp.fc2.weight", "encoder.blocks.4.mlp.fc2.bias", "encoder.blocks.5.norm1.weight", "encoder.blocks.5.norm1.bias", "encoder.blocks.5.attn.qkv.weight", "encoder.blocks.5.attn.qkv.bias", "encoder.blocks.5.attn.proj.weight", "encoder.blocks.5.attn.proj.bias", "encoder.blocks.5.norm2.weight", "encoder.blocks.5.norm2.bias", "encoder.blocks.5.mlp.fc1.weight", "encoder.blocks.5.mlp.fc1.bias", "encoder.blocks.5.mlp.fc2.weight", "encoder.blocks.5.mlp.fc2.bias", "encoder.blocks.6.norm1.weight", "encoder.blocks.6.norm1.bias", "encoder.blocks.6.attn.qkv.weight", "encoder.blocks.6.attn.qkv.bias", "encoder.blocks.6.attn.proj.weight", "encoder.blocks.6.attn.proj.bias", "encoder.blocks.6.norm2.weight", "encoder.blocks.6.norm2.bias", "encoder.blocks.6.mlp.fc1.weight", "encoder.blocks.6.mlp.fc1.bias", "encoder.blocks.6.mlp.fc2.weight", "encoder.blocks.6.mlp.fc2.bias", "encoder.blocks.7.norm1.weight", "encoder.blocks.7.norm1.bias", "encoder.blocks.7.attn.qkv.weight", "encoder.blocks.7.attn.qkv.bias", "encoder.blocks.7.attn.proj.weight", "encoder.blocks.7.attn.proj.bias", "encoder.blocks.7.norm2.weight", "encoder.blocks.7.norm2.bias", "encoder.blocks.7.mlp.fc1.weight", "encoder.blocks.7.mlp.fc1.bias", "encoder.blocks.7.mlp.fc2.weight", "encoder.blocks.7.mlp.fc2.bias", "encoder.blocks.8.norm1.weight", "encoder.blocks.8.norm1.bias", "encoder.blocks.8.attn.qkv.weight", "encoder.blocks.8.attn.qkv.bias", "encoder.blocks.8.attn.proj.weight", "encoder.blocks.8.attn.proj.bias", "encoder.blocks.8.norm2.weight", "encoder.blocks.8.norm2.bias", "encoder.blocks.8.mlp.fc1.weight", "encoder.blocks.8.mlp.fc1.bias", "encoder.blocks.8.mlp.fc2.weight", "encoder.blocks.8.mlp.fc2.bias", "encoder.blocks.9.norm1.weight", "encoder.blocks.9.norm1.bias", "encoder.blocks.9.attn.qkv.weight", "encoder.blocks.9.attn.qkv.bias", "encoder.blocks.9.attn.proj.weight", "encoder.blocks.9.attn.proj.bias", "encoder.blocks.9.norm2.weight", "encoder.blocks.9.norm2.bias", "encoder.blocks.9.mlp.fc1.weight", "encoder.blocks.9.mlp.fc1.bias", "encoder.blocks.9.mlp.fc2.weight", "encoder.blocks.9.mlp.fc2.bias", "encoder.blocks.10.norm1.weight", "encoder.blocks.10.norm1.bias", "encoder.blocks.10.attn.qkv.weight", "encoder.blocks.10.attn.qkv.bias", "encoder.blocks.10.attn.proj.weight", "encoder.blocks.10.attn.proj.bias", "encoder.blocks.10.norm2.weight", "encoder.blocks.10.norm2.bias", "encoder.blocks.10.mlp.fc1.weight", "encoder.blocks.10.mlp.fc1.bias", "encoder.blocks.10.mlp.fc2.weight", "encoder.blocks.10.mlp.fc2.bias", "encoder.blocks.11.norm1.weight", "encoder.blocks.11.norm1.bias", "encoder.blocks.11.attn.qkv.weight", "encoder.blocks.11.attn.qkv.bias", "encoder.blocks.11.attn.proj.weight", "encoder.blocks.11.attn.proj.bias", "encoder.blocks.11.norm2.weight", "encoder.blocks.11.norm2.bias", "encoder.blocks.11.mlp.fc1.weight", "encoder.blocks.11.mlp.fc1.bias", "encoder.blocks.11.mlp.fc2.weight", "encoder.blocks.11.mlp.fc2.bias", "encoder.norm.weight", "encoder.norm.bias", "head.conv1_ctr.0.weight", "head.conv1_ctr.0.bias", "head.conv1_ctr.1.weight", "head.conv1_ctr.1.bias", "head.conv1_ctr.1.running_mean", "head.conv1_ctr.1.running_var", "head.conv2_ctr.0.weight", "head.conv2_ctr.0.bias", "head.conv2_ctr.1.weight", "head.conv2_ctr.1.bias", "head.conv2_ctr.1.running_mean", "head.conv2_ctr.1.running_var", "head.conv3_ctr.0.weight", "head.conv3_ctr.0.bias", "head.conv3_ctr.1.weight", "head.conv3_ctr.1.bias", "head.conv3_ctr.1.running_mean", "head.conv3_ctr.1.running_var", "head.conv4_ctr.0.weight", "head.conv4_ctr.0.bias", "head.conv4_ctr.1.weight", "head.conv4_ctr.1.bias", "head.conv4_ctr.1.running_mean", "head.conv4_ctr.1.running_var", "head.conv5_ctr.weight", "head.conv5_ctr.bias", "head.conv1_offset.0.weight", "head.conv1_offset.0.bias", "head.conv1_offset.1.weight", "head.conv1_offset.1.bias", "head.conv1_offset.1.running_mean", "head.conv1_offset.1.running_var", "head.conv2_offset.0.weight", "head.conv2_offset.0.bias", "head.conv2_offset.1.weight", "head.conv2_offset.1.bias", "head.conv2_offset.1.running_mean", "head.conv2_offset.1.running_var", "head.conv3_offset.0.weight", "head.conv3_offset.0.bias", "head.conv3_offset.1.weight", "head.conv3_offset.1.bias", "head.conv3_offset.1.running_mean", "head.conv3_offset.1.running_var", "head.conv4_offset.0.weight", "head.conv4_offset.0.bias", "head.conv4_offset.1.weight", "head.conv4_offset.1.bias", "head.conv4_offset.1.running_mean", "head.conv4_offset.1.running_var", "head.conv5_offset.weight", "head.conv5_offset.bias", "head.conv1_size.0.weight", "head.conv1_size.0.bias", "head.conv1_size.1.weight", "head.conv1_size.1.bias", "head.conv1_size.1.running_mean", "head.conv1_size.1.running_var", "head.conv2_size.0.weight", "head.conv2_size.0.bias", "head.conv2_size.1.weight", "head.conv2_size.1.bias", "head.conv2_size.1.running_mean", "head.conv2_size.1.running_var", "head.conv3_size.0.weight", "head.conv3_size.0.bias", "head.conv3_size.1.weight", "head.conv3_size.1.bias", "head.conv3_size.1.running_mean", "head.conv3_size.1.running_var", "head.conv4_size.0.weight", "head.conv4_size.0.bias", "head.conv4_size.1.weight", "head.conv4_size.1.bias", "head.conv4_size.1.running_mean", "head.conv4_size.1.running_var", "head.conv5_size.weight", "head.conv5_size.bias". 
	Unexpected key(s) in state_dict: "epoch", "actor_type", "net_type", "net", "net_info", "constructor", "optimizer", "stats", "settings". , how to solve

**Comment by dawnyc** [comment]
You can comment Line 19 and uncomment Line 20 in this file when testing models trained by yourself (https://github.com/dawnyc/ROMTrack/blob/master/lib/test/tracker/ROMTrack.py). The models provided by us only contains the "net" part of the whole checkpoint because the whole checkpoint is too big.

**Comment by Clarkwk** [comment]
> You can comment Line 19 and uncomment Line 20 in this file when testing models trained by yourself (https://github.com/dawnyc/ROMTrack/blob/master/lib/test/tracker/ROMTrack.py). The models provided by us only contains the "net" part of the whole checkpoint because the whole checkpoint is too big.

Ok, thank you for your answer. To train with a single GPU, is it ROMTrack/lib/train/run_training.py? Because there is no training mode for a single GPU in ROMTrack/tracking/train_romtrack.sh file, can you tell me if there are other training mode files？

**Comment by dawnyc** [comment]
For a single GPU, you can just use "--nproc_per_node 1" and it works. For example, you can use the following command:
`
python tracking/train.py --script ROMTrack --config baseline_stage1 --save_dir /YOUR/PATH/TO/SAVE --mode multiple --nproc_per_node 1
`

**Comment by Clarkwk** [comment]
> For a single GPU, you can just use "--nproc_per_node 1" and it works. For example, you can use the following command: `python tracking/train.py --script ROMTrack --config baseline_stage1 --save_dir /YOUR/PATH/TO/SAVE --mode multiple --nproc_per_node 1`

Thank you for your busy reply. When I use the above command you gave python tracking/train.py --script ROMTrack --config got_stage2 --save_dir /media/data/ROMTrack --mode multiple --nproc_per_node 1, Training crashed at epoch 1 with the following error while training the got_stage2 model on a single GPU

Traceback for the error!

Traceback (most recent call last):

File "/media/data/ROMTrack/lib/train/.. /.. /lib/train/trainers/base_trainer.py", line 89, in train

self.train_epoch()

File "/media/data/ROMTrack/lib/train/.. /.. /lib/train/trainers/ltr_trainer.py", line 106, in train_epoch

self.cycle_dataset(loader)

File "/media/data/ROMTrack/lib/train/.. /.. /lib/train/trainers/ltr_trainer.py", line 74, in cycle_dataset

loss, stats = self.actor(data)

File "/media/data/ROMTrack/lib/train/.. /.. /lib/train/actors/ROMTrack.py", line 29, in __call__

out_dict = self.forward_pass(data, self.stage, run_score_head=self.run_score_head)

File "/media/data/ROMTrack/lib/train/.. /.. /lib/train/actors/ROMTrack.py", line 65, in forward_pass

out_dict, _ = self.net.forward_stage2(data['template_images'][0], data['template_images'][1],

The File "anaconda3 / envs/romtrack/lib/python3.6 / site - packages/torch/nn/modules/module. Py", line 1185, in __getattr__

raise AttributeError("'{}' object has no attribute '{}'".format(

AttributeError: 'DistributedDataParallel' object has no attribute 'forward_stage2'



Restarting training from last epoch ...

Finished training!



For the above error, I understand that I only have a single GPU, and the above error still needs multiple Gpus, so what kind of instruction should I use to train on a single GPU is looking forward to your reply.

**Comment by dawnyc** [comment]
I think this is due to your modifaction to the code. Note that you have changed the code `out_dict, _ = self.net.module.forward_stage2(data['template_images'][0], data['template_images'][1],` to `out_dict, _ = self.net.forward_stage2(data['template_images'][0], data['template_images'][1],`, and the keyword "module" is missing. When you are training with "--mode multiple --nproc_per_node 1", you still need the keyword "module".

**Comment by Clarkwk** [comment]
Thank you very much for your answer very much, the above code has been changed back, again the following questions during training, training error,
&nbsp;/ media/data/ROMTrack/lib/train /.. /.. /lib/train/data/loader.py:88: UserWarning:&nbsp; An output with one or more elements was resized since it had shape [2097152],&nbsp; which does not match the required output shape [2, 16, 256, 256].&nbsp; This behavior is deprecated,&nbsp; and in a future PyTorch release outputs will not be resized unless they have zero elements.&nbsp; &nbsp;You can explicitly reuse&nbsp; an out tensor t by resizing it, inplace, to zero elements with t.resize_(0).&nbsp; &nbsp;(Triggered internally at&nbsp; .. /aten/src/ATen/native/Resize.cpp:24.)


return torch.stack (batch, 1, out=out).&nbsp;
May I ask what is the cause of this problem and how to solve it? I really look forward to your reply when you are free.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawnyc/ROMTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawnyc/ROMTrack] train  (Issue #6)





 
I think this is due to your modifaction to the code. Note that you have changed the code out_dict, _ = self.net.module.forward_stage2(data['template_images'][0], data['template_images'][1], to out_dict, _ = self.net.forward_stage2(data['template_images'][0], data['template_images'][1],, and the keyword "module" is missing. When you are training with "--mode multiple --nproc_per_node 1", you still need the keyword "module".

**Comment by Clarkwk** [comment]
> I think this is due to your modifaction to the code. Note that you have changed the code `out_dict, _ = self.net.module.forward_stage2(data['template_images'][0], data['template_images'][1],` to `out_dict, _ = self.net.forward_stage2(data['template_images'][0], data['template_images'][1],`, and the keyword "module" is missing. When you are training with "--mode multiple --nproc_per_node 1", you still need the keyword "module".

Thank you very much for your answer very much, the above code has been changed back, again the following questions during training, training error,
 / media/data/ROMTrack/lib/train /.. /.. /lib/train/data/loader.py:88: UserWarning:  An output with one or more elements was resized since it had shape [2097152],  which does not match the required output shape [2, 16, 256, 256].  This behavior is deprecated,  and in a future PyTorch release outputs will not be resized unless they have zero elements.   You can explicitly reuse  an out tensor t by resizing it, inplace, to zero elements with t.resize_(0).   (Triggered internally at  .. /aten/src/ATen/native/Resize.cpp:24.)

return torch.stack (batch, 1, out=out).
May I ask what is the cause of this problem and how to solve it? I really look forward to your reply when you are free.

**Comment by dawnyc** [comment]
I didn't meet this warning before, perhaps it results from package versions (python, pytorch, etc.). And I think it is just a warning and is not a error. Does it really have an impact on how the code runs?
