### ISSUE TITLE
关于可视化的问题

### ISSUE THREAD

**Issue by lihao0lihao** [dawnyc/ROMTrack#8]
作者你好，请问可视化的代码可以提供吗，我一直不知道特征图和原图像是如何融合的

**Comment by dawnyc** [comment]
We have already provided 2 functions for visualization, i.e., `vis_feature_maps` and `vis_attn_maps` as follows:

`vis_feature_maps`
https://github.com/dawnyc/ROMTrack/blob/1d3b8a88be1f5aa40802c837528feaadd3d25619/lib/test/tracker/tracker_utils.py#L64
`vis_attn_maps`
https://github.com/dawnyc/ROMTrack/blob/1d3b8a88be1f5aa40802c837528feaadd3d25619/lib/test/tracker/tracker_utils.py#L96

Hope this will help you!

**Comment by lihao0lihao** [comment]
谢谢
